### ISSUE TITLE
Compile with avr-g++ instead of avr-gcc

### ISSUE THREAD

**Issue by markd666** [es-ude/EmbeddedSystemsBuildScripts#22]
Hi, I'm struggling to compile a C++ program as compiler defaults to avr-gcc. Is there a way to specify the use of avr-g++ for certain platforms?

**Comment by glencoe** [comment]
Hi Mark,

we never specifically implemented or tested the toolchain for c++ (since no one
here uses it), although
if all apects of the toolchain were created correctly on our side, compiling
c++ should just work and it does for me... The only problem i see when compiling
a small test application is that the compiler complains that `-std=gnu99` is
an invalid flag for c++.

**Comment by markd666** [comment]
Hi Glencoe, thanks for the response and code example. Realised it was compiling c++ fine but build failed because I was trying to include STL files and avr toolchain does support them. 

Forked this repo and trying to build STLport with bazel as an experiment. 

Thanks, 
Mark
